/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auction: typeof import('./src/components/Auction.vue')['default']
    AuctionAlert: typeof import('./src/components/AuctionAlert.vue')['default']
    AuctionDates: typeof import('./src/components/AuctionDates.vue')['default']
    AuctionDetails: typeof import('./src/pages/AuctionDetails.vue')['default']
    Auctions: typeof import('./src/pages/Auctions.vue')['default']
    AuctionTextSection: typeof import('./src/components/AuctionTextSection.vue')['default']
    Bid: typeof import('./src/components/Bid.vue')['default']
    BidHistory: typeof import('./src/components/BidHistory.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CreateAuctionItem: typeof import('./src/pages/CreateAuctionItem.vue')['default']
    Data: typeof import('./src/components/Data.vue')['default']
    Description: typeof import('./src/components/Description.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ImagesViewer: typeof import('./src/components/ImagesViewer.vue')['default']
    Login: typeof import('./src/pages/Login.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Register: typeof import('./src/pages/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
  }
}
